---
subtitle: "Plan d'analyse statistique"
---

```{r info}
rm(list=ls())
library("baseph")
library("tidyverse")
library("kableExtra")
# sessionInfo()
```

# Généralités

Le risque \textalpha{} retenu sera de 0,05 & la puissance de 0,8.

Vu le faible nombre de cas on ne fera pas d'hypothèse de normalité. Les variables numériques seront présentées par leur médiane avec les quartiles & comparées grâce au test non paramétrique de Wilcoxon. Les variables discrètes seront présentés en nombre avec le pourcentage. L'intervalle de confiance (à 95 %) sera calculé par bootstrap (package `boot` [@boot]). Le test du \textchi$^2$ de Spearman sera utilisé sous réserve d'un effectif suffisant, à défaut le test exact de Fischer. Des graphiques seront réalisés pour les résultats importants (package `ggplot2` [@ggplot]).

L'étude comporte deux volets : une enquête de suivi auprès des parents complétée par une analyse du dossier médical & une enquête sur les pratiques courantes auprès des médecins de néonatologie d'Île de France.

## Taille de l'échantillon

Le critère principal est : *Observer le devenir à court terme (réhospitalisation) des nouveau-nés ayant quitté le service de néonatologie de l’hôpital NOVO (site de Pontoise) entre 2012 et 2022 avec un poids inférieur à 2 kilos.* 

Il s'agit d'une étude observationnelle simple pour lesquelles il est difficile de préciser un nombre de cas nécessaires en l'absence de test statistique. Néanmoins on peut estimer à environ quarante cas le strict minimum nécessaire pour avoir un échantillon utilisable s'il n'y a pas trop de données manquantes. 

## Données manquantes

Le décompte des données manquantes sera réalisé & présenté par un tableau ou un graphique. Les variables comportant trop de données manquantes ou non utilisables ne seront pas prises en compte après validation par le promoteur. Les cas où la réhospitalisation de l’enfant (critère principal) n'est pas noté seront exclus. 

Après ce premier tri une imputation des données manquantes (package `missMDA` [@miss]) sera réalisée uniquement pour l'analyse factorielle & pour la recherche du meilleur modèle par step-by-tep descendant pour les analyses par régression (logistique ou linéaire). Néanmoins pour cette analyse, après choix du modèle, le calcul final sera fait avec les données réelles. 

# Description de la population

## Analyse simple

Deux tableaux présenteront les résultats du questionnaire *Parents* : `avant la sortie`  & `au moment du retour`.  La partie médicale de l’enquête sera résumée sur des tableaux complémentaires : caractéristiques cliniques, contexte de naissance & étiologie du retard de croissance.


Une analyse de corrélation (package `corr` [@corr]) entre les variables sera réalisée & présentée sur un graphique de corrélation. Si certaines variables se montrent anormalement corrélées elles devront être exclues de l'étude après accord du promoteur.

Un tableau présentera les résultats du questionnaire *médecin*.

## Analyse factorielle

Si le nombre de cas recueillis le permet une analyse factorielle en MCA (Analyse de correspondances multiples -- package `FactoMineR` [@facto]) sera réalisée.

Cette analyse ne pourra être réalisée qu'après transformation des variables numériques en catégories & imputation des données manquantes ce qui n'est possible que si ces dernières ne sont pas trop nombreuses.

# Objectif principal

*Observer le devenir à court terme (réhospitalisation) des nouveau-nés ayant quitté le service de néonatologie de l’hôpital NOVO (site de Pontoise) entre 2012 et 2022 avec un poids inférieur à 2 kilos.*

Le nombre d'enfants ayant été réhospitalisés durant le mois après sortie de l'hôpital sera présenté en nombre & pourcentage avec son intervalle de confiance. 
 
Une analyse simple sera réalisée pour rechercher d'éventuels facteurs pronostics en utilisant les données médicales (terme, poids à la naissance\dots)


## Analyse par régression

Un modèle de régression logistique multinomiale sera employé (package `VGAM` [@vgam]). Ce modèle de régression permettra d’explorer les facteurs associés à la réponse en utilisant les critères ayant une réponse significative avec un seuil de la p.value \< 0,2 lors de l'étape précédente. Une recherche du meilleur modèle sera réalisée par un step-by-step descendant évaluée par le critère d’information d’Akaike. Cette étape sera réalisée après imputation des données manquantes mais le résultat final sera calculé sur les données vraies. 

# Objectifs secondaires

## Objectifs 1, 2, 3

*Mesure du Z-score pour le poids, la taille & le périmètre crânien, mesuré aux visites systématiques réalisées à 2 mois, 4 mois et 11 mois des nouveau-nés sortis de néonatologie à moins de 2 kilos.*

La médiane avec les quartiles sera présentée pour chacune des trois mesures pour chaque consultation. Une représentation graphique (diagramme en box-plot ou violon-plot) sera réalisée ainsi que des graphiques d'évolution avec les droites de régression \footnote{Pour la visite à onze mois il risque d'y avoir de nombreuses données manquantes ce qui limiterait la qualité du modèle.}. Vu le faible nombre de cas un diagramme *en fagots* pourra être tracé.

Ces mesures seront considérées comme *normales* si comprises entre -2 & 2 DS. Le nombre & le pourcentage de mesures normales seront présentés pour chaque consultation. Des diagrammes de flux (diagramme de Sankey -- package `networkD3` [@reseau]) pour chaque mesure pourront être dessinés.  


## Objectifs 4, 5, 6, 7

Ces critères purement descriptifs issus du questionnaire *parents* reprennent les résultats présentés dans les tableaux descriptifs. Des graphiques pourront être tracés pour présenter ces résultats plus spécifiquement.


## Objectif 8
*Étude des positions médicales concernant le poids minimal de sortie.*

Ces critères purement descriptifs issus du questionnaire *médecins* reprennent les résultats présentés dans les tableaux descriptifs. Des graphiques pourront être tracés pour présenter ces résultats plus spécifiquement.

## Objectif 9
*Caractéristiques cliniques, contexte de naissance, étiologie du retard de croissance.*

Ces critères purement descriptifs issus du  fichier *médical* reprennent les résultats présentés dans les tableaux descriptifs. Des graphiques pourront être tracés pour présenter ces résultats plus spécifiquement.


# Technique {.appendix}

L'analyse statistique sera réalisée avec le logiciel **R**[@rstat] & divers packages. Outre ceux cités dans le texte ou utilisera en particulier `tidyverse` [@tidy] & `baseph` [@baseph].

Un dépôt GitHub sera utilisé qui ne comprendra que le code & non les données ou résultats. Au besoin un faux tableau de données sera présenté pour permettre des tests.

<https://github.com/philippemichel/>
